### ISSUE TITLE
Forbidden (CSRF cookie not set.): /saveprogress

### ISSUE THREAD

**Issue by SonWY2** [chadrick-kwag/segmentation_labeling_tool#1]
'Forbidden (CSRF cookie not set.): /saveprogress'
error occured when through the pages (page down/up key).

so i tried to insert this code in the 'views.py' file.

---------------------------------------------------
from django.http import HttpResponse, JsonResponse
>> from django.views.decorators.csrf import csrf_exempt (line : 5)
from mysite1.settings import STATIC_DIR
import os, json

>> @csrf_exempt (line : 38)
def fetch_image(request, imgno):

---------------------------------------------------
and then, i think it works fine.

**Comment by chadrick-kwag** [comment]
this error seems to occur in Chrome, where the code cannot access the cookies and therefore fails to retreive the csrf token value from the cookies. It looks like access to cookies are disabled by default in chrome due to security reasons.

For the sake of my laziness, I have adopted the issuer's solution in the commit.
